// Code generated by LLM
// THIS NEEDS TO BE REFACTORED HEAVILY

const isToday = (someDate: Date, now: Date) => {
	return (
		someDate.getDate() === now.getDate() &&
		someDate.getMonth() === now.getMonth() &&
		someDate.getFullYear() === now.getFullYear()
	);
};

const isTomorrow = (someDate: Date, now: Date) => {
	const tomorrow = new Date(now);
	tomorrow.setDate(tomorrow.getDate() + 1);
	return (
		someDate.getDate() === tomorrow.getDate() &&
		someDate.getMonth() === tomorrow.getMonth() &&
		someDate.getFullYear() === tomorrow.getFullYear()
	);
};

const getDayName = (someDate: Date) => {
	return [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday",
	][someDate.getDay()];
};

const getMonthName = (someDate: Date) => {
	return [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December",
	][someDate.getMonth()];
};

export function formatEventDate(isoString: string) {
	const date = new Date(isoString);
	const now = new Date();

	let dateString;
	if (isToday(date, now)) {
		dateString = "Today";
	} else if (isTomorrow(date, now)) {
		dateString = "Tomorrow";
	} else {
		const dayDifference = Math.floor((+date - +now) / (1000 * 60 * 60 * 24));
		if (dayDifference < 7) {
			dateString = getDayName(date);
		} else if (date.getFullYear() === now.getFullYear()) {
			dateString = `${getMonthName(date)} ${date.getDate()}`;
		} else {
			dateString = `${getMonthName(date)} ${date.getDate()}, ${date.getFullYear()}`;
		}
	}

	const hours = date.getHours();
	const minutes = date.getMinutes();
	const ampm = hours >= 12 ? "PM" : "AM";
	const formattedHours = hours % 12 || 12; // Convert 24h to 12h format
	const formattedMinutes = minutes < 10 ? "0" + minutes : minutes;
	const timeString = `${formattedHours}:${formattedMinutes} ${ampm}`;

	return `${dateString}, ${timeString}`;
}
